export const ADD_TO_CART="ADD_TO_CART";
export const CHANGE_MESSAGE="CHANGE_MESSAGE";
export const DELETE_ITEM="DELETE_ITEM";
export const INCREASE_ITEM="INCREASE_ITEM";
export const DECREASE_ITEM="DECREASE_ITEM";